---
# tasks file for create_vlan
- name: Create vlan
  ios_vlan:
    vlan_id: "3466"
    name: mini_TEST2
    state: present

- name: Add vlan to Interface Ethernet 1/1
  ios_command:
    commands:
        - conf t
        - interface ethernet 1/1
        - switchport trunk allowed vlan add 3466

- name: Add vlan to Interface Ethernet 1/2
  ios_command:
    commands: 
        - conf t
        - interface ethernet 1/2
        - switchport trunk allowed vlan add 3466

- name: Add vlan to Interface Ethernet 1/3
  ios_command:
    commands: 
        - conf t
        - interface ethernet 1/3
        - switchport trunk allowed vlan add 3466

- name: Add vlan to Interface Ethernet 1/4
  ios_command:
    commands: 
        - conf t
        - interface ethernet 1/4
        - switchport trunk allowed vlan add 3466
...